// 这个页面是母版页，所有的字页面都会嵌套在这个页面中
import Link from 'next/link';
import './globals.css';

// 最终会生成在head标签中，作用是生成SEO相关的数据
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body>
        <Link href='/'>【首页】</Link>
        <Link href='/about'>【关于】</Link>
        <hr />
        {children}
      </body>
    </html>
  );
}
